[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib", "../../node_modules"]
remappings = [
    "@openzeppelin/=../../node_modules/@openzeppelin/",
    "forge-std/=lib/forge-std/src/",
    "contracts/=../../contracts/"
]
solc = "0.8.20"
via_ir = true
optimizer = true
optimizer_runs = 200
fuzz = { runs = 1000 }
invariant = { runs = 256 }
